name: pomodoro_timer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.2
  responsive_framework: ^0.2.0
  audioplayers: ^1.1.1
  get: ^4.6.5
  rate_my_app: ^1.1.3
  # webview_flutter: ^3.0.4
  webviewx: ^0.2.1
  share_plus: ^6.2.0
  numberpicker: ^2.1.2
  flutter_switch: ^0.3.2
  shared_preferences: ^2.0.15
  vibration: ^1.7.6
  wakelock: ^0.6.2
  timezone: 
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^9.5.3
  app_tracking_transparency: ^2.0.3
  # awesome_notifications: any
  http: ^0.13.5
  introduction_screen: ^3.0.2
  url_launcher: ^6.1.6
  flutter_background_service: ^2.4.5
  flutter_background_service_android: ^3.0.3
  firebase_crashlytics: #^3.0.6
  firebase_analytics: #^10.0.6
  firebase_core: #any
  package_info_plus: ^3.1.2
  # webview_flutter: ^2.8.0
  # flutter_native_splash: ^2.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  # flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/white_logo.png"
  image_path_android: "assets/images/white_logo.png"
  image_path_ios: "assets/images/white_logo.png"
  web:
    generate: true
    image_path: "assets/images/white_logo.png"
    background_color: "#0XFFFFFFFF"
    theme_color: "#0XFFFFFFFF"
  windows:
    generate: true
    image_path: "assets/images/white_logo.png"
    icon_size: 48

# Splash Screen Settings
# flutter_native_splash:
#   #general
#   android: true 
#   android12: true 
#   ios: true
#   color: "#212332"
#   image: assets/images/logo.png
#   android_12:
#     image: assets/images/logo.png
#     icon_background_color: "#212332"
    # icon_background_color: "#FFD1A6"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/web/
    - assets/images/
    - assets/sounds/bell.mp3
    - assets/sounds/silence.mp3
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
