import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar': {
          'warning': 'تحذير',
          'error': 'خطأ',
          'no': 'لا',
          'yes': 'أجل',
          'ok': 'حسنا',
          'rateThisApp': 'قيم هذا التطبيق',
          'rateThisAppMessage': 'هل تريد اعجبك هذا التطبيق؟ من فضلك اترك تقيم له',
          'checkThisApp': 'تحقق من هذا التطبيق',
          'privacyPolicy': 'سياسة الخصوصية',
          'termsConditions': 'الشروط والأحكام',
          'share': 'مشاركة',
          'rateUs': 'التقييم',
          'settings': 'الإعدادات',
          ///////////
          'btnTextStart': 'بدأ المؤقت',
          'btnTextResumePomodoro': 'استئناف',
          'btnTextResumeBreak': 'استئناف الاستراحة',
          'btnTextStartShortBreak': 'خذ استراحة قصيرة',
          'btnTextStartLongBreak': 'خذ استراحة طويلة',
          'btnTextStartNewSet': 'بدأ مجموعة جديدة',
          'btnTextPause': 'توقف',
          'btnTextReset': 'إعادة',
          'runningPomodoro': 'المؤقت يعمل، وقت التركيز',
          'pausedPomodoro': 'جاهز للتركيز؟',
          'runningShortBreak': 'حان وقت الاسترخاء والتمتع براحة قصيرة',
          'pausedShortBreak': 'لنحصل على استراحة قصيرة',
          'runningLongBreak': 'حان وقت الاسترخاء والتمتع باستراحة طويلة',
          'pausedLongBreak': 'لنحصل على استراحة طويلة',
          'setFinished': 'تهانينا، انت تستحق استراحة طويلة، أأنت مستعد لها؟',
          "set": 'المجموعة',
          'pomodoriCount': 'عدد الفترات',
          'pomodoroTimer': 'مدة المؤقت',
          'shortBreak': 'الاستراحة القصيرة',
          'longBreak': 'الاستراحة الطويلة',
          'longBreakAfter': 'الاستراحة الطويلة بعد',
          'showNotification': 'إظهار التنبيه',
          'enableAutostart': 'تفعيل البدأ التلقائى',
          'alarmSound': 'صوت التنبيه',
          'vibration': 'الاهتزازات',
          'keepPhoneAwake': 'إبقاء الشاشة مفتوحة',
          'prev': 'السابق',
          'next': 'التالى',
          'skip': 'التخطى',
          'done': 'انتهاء',
          'language': 'اللغة',
          'notificationError': 'حدث خطأ مع التنبيه'
        },
        'en': {
          'warning': 'Warning',
          'error': 'Error',
          'no': 'No',
          'yes': 'Yes',
          'ok': 'Ok',
          'rateThisApp': 'Rate This App',
          'rateThisAppMessage': 'Do you like this app? Please leave a star rating',
          'checkThisApp': 'Check out this app:',
          'privacyPolicy': 'Privacy Policy',
          'termsConditions': 'Terms & Conditions',
          'share': 'Share',
          'rateUs': 'Rate Us',
          'settings': 'Settings',
          ///////
          'btnTextStart': 'START POMODORO',
          'btnTextResumePomodoro': 'RESUME POMODORO',
          'btnTextResumeBreak': 'RESUME BREAK',
          'btnTextStartShortBreak': 'TAKE SHORT BREAK',
          'btnTextStartLongBreak': 'TAKE LONG BREAK',
          'btnTextStartNewSet': 'START NEW SET',
          'btnTextPause': 'PAUSE',
          'btnTextReset': 'RESET',
          'runningPomodoro': 'Pomodoro is running, time to focus',
          'pausedPomodoro': 'Ready to get focus?',
          'runningShortBreak': 'Short break is running, time to relax',
          'pausedShortBreak': 'Let\'s have a short break',
          'runningLongBreak': 'Long break is running, time to relax',
          'pausedLongBreak': 'Let\'s have a long break',
          'setFinished': 'Congrats, you deserve a long break, ready to start?',
          'set': 'SET',
          'pomodoriCount': 'POMODORI COUNT',
          'pomodoroTimer': 'POMODORO TIMER',
          'shortBreak': 'SHORT BREAK',
          'longBreak': 'LONG BREAK',
          'longBreakAfter': 'LONG BREAK AFTER',
          'showNotification': 'SHOW NOTIFICATION',
          'enableAutostart': 'ENABLE AUTOSTART',
          'alarmSound': 'ALARAM SOUND',
          'vibration': 'VIBRATION',
          'keepPhoneAwake': 'KEEP PHONE AWAKE',
          'prev': 'PREVIOUS',
          'next': 'NEXT',
          'skip': 'SKIP',
          'done': 'DONE',
          'language': 'Language',
          'notificationError': 'There was an error with notifications'
        },
      };
}
